const restaurantsData = [
  { type: "chinese", restaurantName: "Dragon Palace" },
  { type: "france", restaurantName: "Le Bistro" },
  { type: "hamburger", restaurantName: "Burger Barn" },
  { type: "greek", restaurantName: "Olive Garden" },
  { type: "italian", restaurantName: "Pasta Paradise" },
  { type: "mexican", restaurantName: "El Ranchito" },
  { type: "indian", restaurantName: "Taj Mahal" },
  { type: "japanese", restaurantName: "Sakura Sushi" },
  { type: "thai", restaurantName: "Thai Spice" },
  { type: "mediterranean", restaurantName: "Cedar Tree" },
  { type: "chinese", restaurantName: "Jade Palace" },
  { type: "chinese", restaurantName: "Phoenix Dragon" },
  { type: "chinese", restaurantName: "Golden Lotus" },
  { type: "chinese", restaurantName: "Silk Road" },
  { type: "chinese", restaurantName: "Mandarin Garden" },
  { type: "france", restaurantName: "La Tour" },
  { type: "france", restaurantName: "Bistro du Paris" },
  { type: "france", restaurantName: "Le Petit Paris" },
  { type: "france", restaurantName: "Café de la Seine" },
  { type: "france", restaurantName: "Le Croissant" },
  { type: "hamburger", restaurantName: "Burger Haven" },
  { type: "hamburger", restaurantName: "Patty Palace" },
  { type: "hamburger", restaurantName: "Burger Bistro" },
  { type: "hamburger", restaurantName: "Hamburger Hut" },
  { type: "hamburger", restaurantName: "Burger Bazaar" },
  { type: "greek", restaurantName: "Zeus's Olive" },
  { type: "greek", restaurantName: "Athena's Garden" },
  { type: "greek", restaurantName: "Olive's Delight" },
  { type: "greek", restaurantName: "Greek Gourmet" },
  { type: "greek", restaurantName: "Olive's Haven" },
  { type: "italian", restaurantName: "Pasta Perfection" },
  { type: "italian", restaurantName: "Roma's Restaurant" },
  { type: "italian", restaurantName: "Pasta Pinnacle" },
  { type: "italian", restaurantName: "Italian Elegance" },
  { type: "italian", restaurantName: "Pasta Paradise II" },
  { type: "mexican", restaurantName: "El Ranchito Grande" },
  { type: "mexican", restaurantName: "Mexican Magic" },
  { type: "mexican", restaurantName: "El Ranchito Express" },
  { type: "mexican", restaurantName: "Mexican Mansion" },
  { type: "mexican", restaurantName: "El Ranchito Deluxe" },
  { type: "indian", restaurantName: "Taj Mahal II" },
  { type: "indian", restaurantName: "Indian Infinity" },
  { type: "indian", restaurantName: "Taj Mahal Express" },
  { type: "indian", restaurantName: "Indian Illusion" },
  { type: "indian", restaurantName: "Taj Mahal Deluxe" },
  { type: "japanese", restaurantName: "Sakura Sushi II" },
  { type: "japanese", restaurantName: "Japanese Journey" },
  { type: "japanese", restaurantName: "Sakura Sushi Express" },
  { type: "japanese", restaurantName: "Japanese Junction" },
  { type: "japanese", restaurantName: "Sakura Sushi Deluxe" },
  { type: "thai", restaurantName: "Thai Thrill" },
  { type: "thai", restaurantName: "Thai Treasure" },
  { type: "thai", restaurantName: "Thai Thrive" },
  { type: "thai", restaurantName: "Thai Triumph" },
  { type: "thai", restaurantName: "Thai Throne" },
  { type: "mediterranean", restaurantName: "Cedar Tree II" },
  { type: "mediterranean", restaurantName: "Mediterranean Magic" },
  { type: "mediterranean", restaurantName: "Cedar Tree Express" },
  { type: "mediterranean", restaurantName: "Mediterranean Mansion" },
  { type: "mediterranean", restaurantName: "Cedar Tree Deluxe" },
];
module.exports = { restaurantsData };
