const restaurantsData = [
  { type: "chinese", restaurantName: "Dragon Palace" },
  { type: "france", restaurantName: "Le Bistro" },
  { type: "hamburger", restaurantName: "Burger Barn" },
  { type: "greek", restaurantName: "Olive Garden" },
  { type: "italian", restaurantName: "Pasta Paradise" },
  { type: "mexican", restaurantName: "El Ranchito" },
  { type: "indian", restaurantName: "Taj Mahal" },
  { type: "japanese", restaurantName: "Sakura Sushi" },
  { type: "thai", restaurantName: "Thai Spice" },
  { type: "mediterranean", restaurantName: "Cedar Tree" },
  { type: "chinese", restaurantName: "Jade Palace" },
  { type: "chinese", restaurantName: "Phoenix Dragon" },
  { type: "chinese", restaurantName: "Golden Lotus" },
  { type: "chinese", restaurantName: "Silk Road" },
  { type: "chinese", restaurantName: "Mandarin Garden" },
  { type: "france", restaurantName: "La Tour" },
  { type: "france", restaurantName: "Bistro du Paris" },
  { type: "france", restaurantName: "Le Petit Paris" },
  { type: "france", restaurantName: "Café de la Seine" },
  { type: "france", restaurantName: "Le Croissant" },
  { type: "hamburger", restaurantName: "Burger Haven" },
  { type: "hamburger", restaurantName: "Patty Palace" },
  { type: "hamburger", restaurantName: "Burger Bistro" },
  { type: "hamburger", restaurantName: "Hamburger Hut" },
  { type: "hamburger", restaurantName: "Burger Bazaar" },
  { type: "greek", restaurantName: "Zeus's Olive" },
  { type: "greek", restaurantName: "Athena's Garden" },
  { type: "greek", restaurantName: "Olive's Delight" },
  { type: "greek", restaurantName: "Greek Gourmet" },
  { type: "greek", restaurantName: "Olive's Haven" },
  { type: "italian", restaurantName: "Pasta Perfection" },
  { type: "italian", restaurantName: "Roma's Restaurant" },
  { type: "italian", restaurantName: "Pasta Pinnacle" },
  { type: "italian", restaurantName: "Italian Elegance" },
  { type: "italian", restaurantName: "Pasta Paradise II" },
  { type: "mexican", restaurantName: "El Ranchito Grande" },
  { type: "mexican", restaurantName: "Mexican Magic" },
  { type: "mexican", restaurantName: "El Ranchito Express" },
  { type: "mexican", restaurantName: "Mexican Mansion" },
  { type: "mexican", restaurantName: "El Ranchito Deluxe" },
  { type: "indian", restaurantName: "Taj Mahal II" },
  { type: "indian", restaurantName: "Indian Infinity" },
  { type: "indian", restaurantName: "Taj Mahal Express" },
  { type: "indian", restaurantName: "Indian Illusion" },
  { type: "indian", restaurantName: "Taj Mahal Deluxe" },
  { type: "japanese", restaurantName: "Sakura Sushi II" },
  { type: "japanese", restaurantName: "Japanese Journey" },
  { type: "japanese", restaurantName: "Sakura Sushi Express" },
  { type: "japanese", restaurantName: "Japanese Junction" },
  { type: "japanese", restaurantName: "Sakura Sushi Deluxe" },
  { type: "thai", restaurantName: "Thai Thrill" },
  { type: "thai", restaurantName: "Thai Treasure" },
  { type: "thai", restaurantName: "Thai Thrive" },
  { type: "thai", restaurantName: "Thai Triumph" },
  { type: "thai", restaurantName: "Thai Throne" },
  { type: "mediterranean", restaurantName: "Cedar Tree II" },
  { type: "mediterranean", restaurantName: "Mediterranean Magic" },
  { type: "mediterranean", restaurantName: "Cedar Tree Express" },
  { type: "mediterranean", restaurantName: "Mediterranean Mansion" },
  { type: "mediterranean", restaurantName: "Cedar Tree Deluxe" },
];
const additionalRestaurants = [
  { type: "american", restaurantName: "Uncle Sam's Diner" },
  { type: "sushi", restaurantName: "Blue Ocean Sushi" },
  { type: "steak", restaurantName: "Prime Cuts Steakhouse" },
  { type: "vegetarian", restaurantName: "Green Leaf Cafe" },
  { type: "vegan", restaurantName: "Plant Power Bistro" },
  { type: "seafood", restaurantName: "Ocean's Bounty Restaurant" },
  { type: "french", restaurantName: "Cuisine de France" },
  { type: "barbecue", restaurantName: "Smokehouse Grill" },
  { type: "korean", restaurantName: "Kimchi Kingdom" },
  { type: "spanish", restaurantName: "Tapas Time" },
];
const RestaurantsAddress = [
  { streetNumber: "8", streetName: "Rothschild Boulevard" },
  { streetNumber: "12", streetName: "Dizengoff Street" },
  { streetNumber: "5", streetName: "Allenby Street" },
  { streetNumber: "17", streetName: "Ibn Gabirol Street" },
  { streetNumber: "3", streetName: "Ben Yehuda Street" },
  { streetNumber: "10", streetName: "HaYarkon Street" },
  { streetNumber: "16", streetName: "Herzl Street" },
  { streetNumber: "4", streetName: "King George Street" },
  { streetNumber: "18", streetName: "HaHashmonaim Street" },
  { streetNumber: "7", streetName: "Arlozorov Street" },
  { streetNumber: "15", streetName: "Ahad Ha'am Street" },
  { streetNumber: "9", streetName: "Ben Gurion Boulevard" },
  { streetNumber: "11", streetName: "Shenkin Street" },
  { streetNumber: "6", streetName: "Frishman Street" },
  { streetNumber: "14", streetName: "Bialik Street" },
  { streetNumber: "2", streetName: "Bograshov Street" },
  { streetNumber: "19", streetName: "Nahalat Binyamin Street" },
  { streetNumber: "1", streetName: "Yehuda HaLevi Street" },
  { streetNumber: "20", streetName: "Montefiore Street" },
  { streetNumber: "13", streetName: "Rabin Square" },
  { streetNumber: "10", streetName: "Nahalat Itzhak Street" },
  { streetNumber: "3", streetName: "Yarkon Street" },
  { streetNumber: "8", streetName: "Nordau Boulevard" },
  { streetNumber: "2", streetName: "Kaplan Street" },
  { streetNumber: "16", streetName: "Hayarkon Street" },
  { streetNumber: "7", streetName: "Yefet Street" },
  { streetNumber: "6", streetName: "Bnei Dan Street" },
  { streetNumber: "18", streetName: "Hasharon Street" },
  { streetNumber: "13", streetName: "HaRav Kook Street" },
  { streetNumber: "14", streetName: "Yosef Levi Street" },
  { streetNumber: "1", streetName: "Gordon Street" },
  { streetNumber: "12", streetName: "Yehuda HaMaccabi Street" },
  { streetNumber: "5", streetName: "Ben Ami Street" },
  { streetNumber: "4", streetName: "HaMasger Street" },
  { streetNumber: "11", streetName: "Retsif HaAliyah HaShniya Street" },
  { streetNumber: "15", streetName: "HaPalmach Street" },
  { streetNumber: "19", streetName: "Weizmann Street" },
  { streetNumber: "20", streetName: "LaSalle Street" },
  { streetNumber: "9", streetName: "Pinhas Rozen Street" },
  { streetNumber: "17", streetName: "Allenby Park" },
  { streetNumber: "8", streetName: "Nakhum Gutman Street" },
  { streetNumber: "2", streetName: "Wingate Street" },
  { streetNumber: "18", streetName: "Yitzhak Sadeh Street" },
  { streetNumber: "3", streetName: "Nachmani Street" },
  { streetNumber: "1", streetName: "HaHashmal Street" },
  { streetNumber: "6", streetName: "Beit HaDfus Street" },
  { streetNumber: "10", streetName: "Hayarkon Park" },
  { streetNumber: "12", streetName: "Eliyahu Golomb Street" },
  { streetNumber: "14", streetName: "Rothschild Park" },
  { streetNumber: "7", streetName: "Aharon Chelouche Street" },
  { streetNumber: "16", streetName: "Sha'ul HaMelech Street" },
  { streetNumber: "5", streetName: "Yona HaNavi Street" },
  { streetNumber: "4", streetName: "Zevulun Street" },
  { streetNumber: "19", streetName: "Shaul Tchernichovsky Street" },
  { streetNumber: "20", streetName: "Pinsker Street" },
  { streetNumber: "13", streetName: "HaTachana - The Old Railway Station" },
  { streetNumber: "11", streetName: "Ben Zion Boulevard" },
  { streetNumber: "1", streetName: "David Bloch Street" },
  { streetNumber: "15", streetName: "Ussishkin Street" },
  { streetNumber: "9", streetName: "Arnon Street" },
];

module.exports = { restaurantsData, additionalRestaurants, RestaurantsAddress };
